version: '3.6'

services:
  application:
    user: "${UID:-1000}:${GID:-1000}" #don't run as root by default to prevent permission conflicts
    build:
      context: docker/application
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./:/app
      - $HOME/.phive:/home/application/.phive
      - $HOME/.ssh:/home/application/.ssh
      - $HOME/.gitconfig:/home/application/.gitconfig
      - ${SSH_AUTH_SOCK:-/ssh-agent}:/ssh-agent # Forward local machine SSH key to docker
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - docker/application/environment.yml
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
