name: Post Release
on:
  release:
    types: [ published ]

jobs:
  update_default_branch:
    name: Update default branch after published release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "main"

      - name: create changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_labels: "duplicate,question,invalid,wontfix,skip-changelog"

      - name: commit updated changelog
        uses: EndBug/add-and-commit@v7
        with:
          message: "[CHANGELOG] Updated changelog"
          add: "CHANGELOG.md"
          signoff: true
          branch: main

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release"
          destination_branch: "main"
          pr_title: "[Deployment] Update default branch"
          pr_label: "skip-changelog"
          github_token: ${{ secrets.GITHUB_TOKEN }}