name: Update Changelog
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  release:
    types: [ published ]

jobs:
  update_changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_labels: "duplicate,question,invalid,wontfix,skip-changelog"

      - name: commit updated changelog
        uses: EndBug/add-and-commit@v6
        with:
          message: "[CHANGELOG] Updated changelog"
          add: "CHANGELOG.md"
          signoff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_changelog_after_release:
    name: Update changelog in default branch after published release
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: create changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_labels: "duplicate,question,invalid,wontfix,skip-changelog"

      - name: commit updated changelog
        uses: EndBug/add-and-commit@v6
        with:
          message: "[CHANGELOG] Updated changelog"
          add: "CHANGELOG.md"
          signoff: true
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}